# Generated by Django 2.1.2 on 2018-10-21 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='creators',
            fields=[
                ('creator_name', models.CharField(db_index=True, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('creator_email', models.EmailField(max_length=254)),
                ('creator_password', models.CharField(db_index=True, max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='script',
            fields=[
                ('script_name', models.CharField(db_index=True, max_length=40, primary_key=True, serialize=False, unique=True)),
                ('script', models.TextField()),
                ('create_date', models.DateField(default='2018-10-21')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Script.creators')),
            ],
        ),
    ]
