# Generated by Django 2.1.2 on 2018-10-28 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Script', '0005_auto_20181028_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='creator',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
