# Generated by Django 2.1.2 on 2018-11-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Script', '0014_auto_20181105_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AlterField(
            model_name='history',
            name='run_time',
            field=models.DateTimeField(default='2018-11-05 19:19:11.819523'),
        ),
    ]
