# Generated by Django 2.1.2 on 2018-11-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Script', '0016_auto_20181108_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='run_time',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='script',
            name='create_date',
            field=models.DateField(default='2018-11-13'),
        ),
    ]
