# Generated by Django 2.1.2 on 2018-11-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Script', '0017_auto_20181113_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='script_format',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='script',
            name='create_date',
            field=models.DateField(default='2018-11-15'),
        ),
    ]
