# Generated by Django 2.1.2 on 2018-11-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Script', '0018_auto_20181115_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script_from_github',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=100)),
                ('zip_file', models.FileField(upload_to='')),
            ],
        ),
    ]
