# Generated by Django 2.0.5 on 2018-11-27 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Script', '0022_auto_20181127_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='patameter',
            new_name='parameter',
        ),
    ]
