# Generated by Django 2.0.5 on 2018-11-27 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Script', '0023_auto_20181127_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='code',
            new_name='console_output',
        ),
        migrations.AddField(
            model_name='history',
            name='output',
            field=models.TextField(default=''),
        ),
    ]
