# Generated by Django 2.0.5 on 2018-11-27 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Script', '0024_auto_20181127_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='output',
            new_name='status',
        ),
    ]
