# Generated by Django 2.0.5 on 2018-11-01 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Script', '0007_auto_20181101_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.DateField(default='2018-11-01 21:36:20.808198')),
                ('host_script', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Script.script')),
            ],
        ),
    ]
