# Generated by Django 2.1.2 on 2018-11-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Script', '0010_auto_20181105_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='run_time',
            field=models.DateField(default='2018-11-05 17:26:00.026861'),
        ),
    ]
