# Generated by Django 2.1.2 on 2018-11-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Script', '0011_auto_20181105_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='run_time',
            field=models.DateTimeField(default='2018-11-05 17:26:58.121318'),
        ),
    ]
