# Generated by Django 2.1.2 on 2018-11-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Script', '0012_auto_20181105_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.AlterField(
            model_name='history',
            name='run_time',
            field=models.DateTimeField(default='2018-11-05 17:29:17.445520'),
        ),
    ]
