# Generated by Django 2.1.2 on 2018-11-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Script', '0013_auto_20181105_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
        migrations.AlterField(
            model_name='history',
            name='run_time',
            field=models.DateTimeField(default='2018-11-05 17:32:24.283110'),
        ),
    ]
