# Generated by Django 2.1.2 on 2018-11-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Script', '0019_script_from_github'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script_from_github',
            name='zip_file',
            field=models.FileField(upload_to='Script/static/git files'),
        ),
    ]
